# Generated by Django 4.2.10 on 2024-02-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0003_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
