# Generated by Django 4.2.10 on 2024-02-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0004_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
