# Generated by Django 4.2.10 on 2024-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0005_alter_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite'), ('delux', 'Delux Room')], help_text='Select the type of room.', max_length=10)),
                ('description', models.TextField(help_text='Provide a description of the room.')),
                ('amenities', models.TextField(help_text='List the amenities available in the room.')),
                ('occupancy', models.PositiveIntegerField(help_text='Specify the maximum number of guests allowed in the room.')),
                ('room_size', models.CharField(help_text='Enter the size of the room.', max_length=50)),
                ('availability', models.BooleanField(default=True, help_text='Indicate if the room is currently available for booking.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price per night for the room.', max_digits=10)),
                ('additional_services', models.TextField(help_text='Specify any additional services offered with the room.')),
                ('accessibility_features', models.TextField(help_text='Describe any accessibility features of the room.')),
            ],
        ),
    ]
