# Generated by Django 4.2.10 on 2024-02-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0006_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='accessibility_features',
        ),
        migrations.RemoveField(
            model_name='room',
            name='additional_services',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
    ]
