# Generated by Django 4.2.10 on 2024-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0007_remove_room_accessibility_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='no_of_bath',
            field=models.PositiveBigIntegerField(help_text='Specify number of Baths', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='no_of_bed',
            field=models.PositiveBigIntegerField(help_text='Specify number of Beds', null=True),
        ),
    ]
