# Generated by Django 4.2.10 on 2024-02-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0008_room_no_of_bath_room_no_of_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite Room'), ('delux', 'Delux Room')], help_text='Select the type of room.', max_length=10),
        ),
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_booked', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_main.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
