# Generated by Django 4.2.10 on 2024-02-20 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0009_alter_room_room_type_bookroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
