# Generated by Django 4.2.10 on 2024-02-24 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0010_alter_bookroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='generated_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
