# Generated by Django 4.2.10 on 2024-02-24 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hms_main', '0011_bookroom_generated_id_alter_bookroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='generated_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
